require 'asteroids/systems/image_render'
require 'asteroids/systems/player_input'
require 'asteroids/systems/movement'
require 'asteroids/systems/off_screen'
require 'asteroids/systems/shoot'
require 'asteroids/systems/bullet_despawn'
require 'asteroids/systems/asteroid_spawn'
require 'asteroids/systems/asteroid_despawn'
require 'asteroids/systems/asteroid_bullet_collision'
require 'asteroids/systems/asteroid_player_collision'
require 'asteroids/systems/aabb_update'
require 'asteroids/systems/restart_game'

require 'asteroids/systems/ui_render'